### ISSUE TITLE
Vector iterator bug

### ISSUE THREAD

**Issue by rtheunissen** [xiaq/persistent#4]
While running some benchmarks, I came across a panic:

> cannot advance; vector iterator bug

Under what conditions might this occur? Is this a bug you are already aware of? 
I can try to come up with an example that reproduces this bug.

**Comment by xiaq** [comment]
Hmm, I am not aware of this bug. When you see this it is definitely a bug...

**Comment by rtheunissen** [comment]
I was adding `nil` values which trips the `e.node[e.index+1] != nil` case.

**Comment by rtheunissen** [comment]
I still think this is a bug unless nil values aren't supported. Maybe a sentinel value could be used? Or a length-based check?
